# Generated by Django 4.2.4 on 2024-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
