# Generated by Django 4.2.4 on 2024-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emp_id',
            field=models.CharField(default='UNKNOWN', max_length=100, unique=True),
        ),
    ]
