# Generated by Django 4.2.4 on 2024-07-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
